# Generated by Django 3.1.5 on 2021-01-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recycler',
            old_name='primary_phone_number',
            new_name='phone_number',
        ),
    ]
