# Generated by Django 3.1.5 on 2021-01-24 07:48

from django.db import migrations, models
import recycle.models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0002_auto_20210123_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycler',
            name='customer_number',
            field=models.IntegerField(default=recycle.models.increment_invoice_number),
        ),
    ]
